# -*- coding: utf-8 -*-
"""Using fuction in Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YcNrQpugaYpCo_QhZDtFPePO-uOeNwHR

Exercise 1
Read a temperature in degrees Celsius and display it converted to degrees Fahrenheit. The conversion formula is F = (9 * C + 160) / 5, where F is the temperature in Fahrenheit and C is the temperature in degrees Celsius
"""

def read_temperature():
  temperature = float(input('wrtite the temperature in celsius: '))
  return temperature

def toConvert(temperature_celsius):
  temperature_f = (9 * temperature_celsius + 160) / 5
  return temperature_f

def show(temperature_f):
  print(temperature_f)

temperature_c = read_temperature()
temperature_f = toConvert(temperature_c)
show(temperature_f)